# Generated by Django 5.0.6 on 2024-05-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendorf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_vendor', models.CharField(max_length=20)),
                ('visiting_place', models.CharField(max_length=40)),
                ('duration', models.IntegerField()),
                ('departure_date', models.CharField(max_length=40)),
                ('accomodation', models.CharField(max_length=40)),
                ('transportation', models.CharField(max_length=40)),
                ('contact_no', models.IntegerField()),
            ],
        ),
    ]
